
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.networking
- cluster.mcp_test.openstack
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.0.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.0.qcow2

    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 20.10.2.2
    infra_config_deploy_address: 20.10.1.2

    cluster_domain: mcp_test.local
    cluster_name: mcp_test
    cluster_public_host: ${_param:openstack_proxy_address}


  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
