classes:
- system.linux.system.repo.mcp10
- service.keepalived.cluster.single
- system.glusterfs.server.cluster
- system.salt.control.virt
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_telemetry_cluster
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
    keepalived_vip_interface: br_ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: eth0
    primary_first_nic: eth1
    primary_second_nic: eth2
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##Default production sizing
        openstack.control:
          cpu: 8
          ram: 32768
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 8
          ram: 16384
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 8
          ram: 32768
          disk_profile: small
          net_profile: default
        openstack.telemetry:
          cpu: 8
          ram: 32768
          disk_profile: xxlarge
          net_profile: default
        openstack.proxy:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 8
          ram: 32768
          disk_profile: small
          net_profile: default
        opencontrail.analytics:
          cpu: 8
          ram: 32768
          disk_profile: large
          net_profile: default
        stacklight.log:
          cpu: 4
          ram: 8192
          disk_profile: xxlarge
          net_profile: default
        stacklight.server:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: default
        stacklight.telemetry:
          cpu: 4
          ram: 8192
          disk_profile: xxlarge
          net_profile: default
      cluster:
        internal:
          node:
            prx02:
              provider: ${_param:infra_compute_node03_address}.${_param:cluster_domain}
            mdb01:
              image: ${_param:salt_control_xenial_image}
            mdb02:
              image: ${_param:salt_control_xenial_image}
            mdb03:
              image: ${_param:salt_control_xenial_image}
  virt:
    nic:
      default:
        eth2:
          bridge: br_mgm
        eth1:
          bridge: br_ctl
  linux:
    network:
      interface:
        eth0:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:deploy_nic}
        eth1:
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_first_nic}
          master: bond0
        eth2:
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_second_nic}
          master: bond0
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          name_servers:
          - ${_param:dns_server01}
          - ${_param:dns_server02}
          use_interfaces:
          - ${_param:deploy_nic}
        bond0:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - ${_param:primary_first_nic}
          - ${_param:primary_second_nic}
          slaves: ${_param:primary_first_nic} ${_param:primary_second_nic}
          mode: active-backup
        bond0.1:
          name: bond0.${_param:control_vlan}
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - bond0
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          use_interfaces:
          - bond0.${_param:control_vlan}
  #   system:
  #     package:
  #       linux-image-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39-generic:
  #         version: latest
  #       linux-image-extra-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39:
  #         version: latest
  #     user:
  #       root:
  #         enabled: true
  #         name: root
  #         home: /root
  #         # Password is cloudlab, comment out, configure your SSH key bellow
  #         # and disable password auth
  #         password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./
